tickers:
  - AAPL
  # - MSFT
  # - ^GSPC
  - ^VIX
  # - AMZN
period: "5y"
interval: "1d"
volatility_windows: [5, 10, 20]
date_filter:
  start: "2020-01-01"
  end: "2024-12-31"
market_proxy_processing:
  default_market_vola_proxy: "^VIX"
  type: "zscore"  # or "returns", "raw", "smoothed"
  smoothing_window: 5

volatility_processing:
  normalize: true
  method: "zscore"  # or "minmax" or "log"