# model.yaml

# HMM model hyperparameters

# HMM-specific configuration
HMMModel:
  covariance_type: "full"
  random_seed: 13
  init_params: "stmc"
  n_iter: 100
  tol: 1e-4
  n_fits: 100
  max_components: 2

# Split config
split:
  method: "default"
  train_size: 0.8
  shuffle: false

# Evaluation metric
evaluation_metric: "LogLikelihoodWithEntropy"
entropy_weight: 10